baseURL = "https://www.csvresearch.com/"
languageCode = "en-us"
title = "CSV SOLUTIONS"
theme = "hugo-hero-theme"

[params]
  google_analytics_id="G-Z8GJ7GZJEN"

  [params.homepage_meta_tags]
    meta_description = "CSV Research solutions is aimed at providing data science solutions for better understanding of data. It also focuses on machine learning to inform better planning."
    meta_og_title = "CSV RESEARCH SOLUTIONS"
    meta_og_type = "website"
    meta_og_url = "https://csvresearch.com/"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-hero-theme/master/images/tn.png"
    meta_og_description = "CSV solutions is aimed at providing data science solutions for better understanding of data. It also focuses on machine learning to inform better planning"
    meta_twitter_card = "summary"
    meta_twitter_site = "@csvsolutions"
    meta_twitter_creator = "@csvsolutions"
    
[[menu.main]]
	name = "Services"
	url = "/services/"
    weight = 1

[[menu.main]]
    name = "Posts"
    url = "/work/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3


[[menu.main]]
    name = "History"
    url = "/history/"
    weight = 3

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4
    
[[menu.main]]
    name = "LinkedIn"
    icon = "fa fa-linkedin"
    url = "https://www.linkedin.com/company/csvresearchsolutions/"
    weight = 5
    
[[menu.main]]
    name = "Github"
    icon = "fa fa-github"
    weight = 6
    url = "https://github.com/csvsolutions/"
    
[[menu.main]]
    name = "YouTube"
    icon = "fa fa-youtube"
    weight = 7
    url = "https://www.youtube.com/channel/UC-YubzT01YgvBDDQp6UbzxA/about"
  
[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
  
