baseURL = "https://csvsolutions.netlify.app"
languageCode = "en-us"
title = "CSV SOLUTIONS"
theme = "hugo-hero-theme"

[params]
  google_analytics_id=""

  [params.homepage_meta_tags]
    meta_description = "CSV solutions is aimed at providing data science solutions for better understanding of data. It also focuses on machine learning to inform better planning."
    meta_og_title = "CSV SOLUTIONS"
    meta_og_type = "website"
    meta_og_url = "https://csvsolutions.netlify.app"
    meta_og_image = "https://raw.githubusercontent.com/JugglerX/hugo-hero-theme/master/images/tn.png"
    meta_og_description = "CSV solutions is aimed at providing data science solutions for better understanding of data. It also focuses on machine learning to inform better planning"
    meta_twitter_card = "summary"
    meta_twitter_site = "@csvsolutions"
    meta_twitter_creator = "@csvsolutions"

[[menu.main]]
	name = "Services"
	url = "/services/"
    weight = 1

[[menu.main]]
    name = "Work"
    url = "/work/"
    weight = 2

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 3


[[menu.main]]
    name = "History"
    url = "/history/"
    weight = 3

[[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 4

[permalinks]
  post = "/:year/:month/:day/:slug/"
  pages = "/:filename/"
